name: flutter_paste_input
description: A Flutter plugin for intercepting paste events in TextFields, supporting text and image content across all platforms.
version: 1.0.0
homepage: https://github.com/gausoft/flutter_paste_input
repository: https://github.com/gausoft/flutter_paste_input
issue_tracker: https://github.com/gausoft/flutter_paste_input/issues

topics:
  - clipboard
  - paste
  - images
  - text-input
  - textfield

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^22.7.4

flutter:
  plugin:
    platforms:
      android:
        package: dev.gausoft.flutter_paste_input
        pluginClass: FlutterPasteInputPlugin
      ios:
        pluginClass: FlutterPasteInputPlugin
      linux:
        pluginClass: FlutterPasteInputPlugin
      macos:
        pluginClass: FlutterPasteInputPlugin
      windows:
        pluginClass: FlutterPasteInputPluginCApi
